<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Connected Services\**" />
    <EmbeddedResource Remove="Connected Services\**" />
    <None Remove="Connected Services\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Win.Design" Version="24.2.13" />
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
      <CustomToolNamespace>WinForms.Client.Properties</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
</Project>